[package]
name = "HydraLinkGenerator"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
regex = "1.11.0"
reqwest = "0.12.8"
scraper = "0.20.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = ["full"] }
